language: ruby
cache: bundler 
before_install: gem update bundler
install:
  - bundle install
script:
  - "jekyll build"
branches:
  only:
  - master
sudo: false
deploy:
  github_token: $GITHUB_TOKEN
  provider: pages
  skip_cleanup: true
  local_dir: _site/
  keep_history: true
  on:
    branch: master
