language: ruby
rvm:
  - 2.6
cache:
  directories:
    - /home/travis/.rvm/
before_install:
install:
  - bundle install
script:
  - "bundle exec jekyll build"
branches:
  only:
  - master
sudo: false
deploy:
  github_token: $GITHUB_TOKEN
  provider: pages
  skip_cleanup: true
  local_dir: _site/
  keep_history: true
  on:
    branch: master
