#!/bin/sh

git config --global user.name $GITHUB_USER
git config --global user.email $GITHUB_EMAIL
git add docs
git commit -m "Lastest site built on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to github"
git remote add origin "https://$GITHUB_USER:$GITHUB_PW@$REPO"
git push origin master  