#!/bin/sh

./build

git config --global user.name $GITHUB_USER
git config --global user.email $GITHUB_EMAIL
git add -A
git status
git commit -m "Lastest site built on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to github"
git push "https://$GITHUB_USER:$GITHUB_PW@$REPO" master:master  